'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {getObjectives,getProgress,itemCompletion,objectiveDone,type ClassRecord,type Item,type Objective} from './curriculum';
type Props={c:ClassRecord;item:Item;disabled:boolean;onDone:(value:boolean)=>void;onObjective:(objective:Objective,value:boolean)=>void;onHours:(key:'planned'|'taught',value:number)=>void};
export function SubtopicChecklist({c,item,disabled,onDone,onObjective,onHours}:Props){
 const list=getObjectives(item),r=getProgress(c,item),m=itemCompletion(c,item),id=`${c.id}-${item.id}`;
 return <details className="subtopic"><summary><div><span className="subtopic-code">{item.id}{item.hl?' · HL only':''}</span><h3>{item.title}</h3><span className="subtopic-status">{list.length?`${m.done}/${m.count} syllabus items complete`:r.done?'Complete':'Not complete'} · {r.planned} h planned · {r.taught} h taught</span></div><span className="disclosure-icon" aria-hidden="true">⌄</span></summary><div className="subtopic-controls"><div className="bulk-check"><Checkbox id={`${id}-all`} aria-label={`Complete ${item.title}`} checked={m.done===m.count?true:m.done>0?'indeterminate':false} disabled={disabled} onCheckedChange={v=>onDone(v===true)}/><label htmlFor={`${id}-all`}>{list.length?'Mark all items complete':'Mark component complete'}</label></div><label>Planned h<Hours key={`${id}-p-${r.planned}`} label={`${item.title} planned hours`} value={r.planned} min={.25} disabled={disabled} save={v=>onHours('planned',v)}/></label><label>Taught h<Hours key={`${id}-t-${r.taught}`} label={`${item.title} taught hours`} value={r.taught} min={0} disabled={disabled} save={v=>onHours('taught',v)}/></label></div>{list.length>0&&<p className="detail-help">Check each syllabus item as it is taught. Expand its title for teaching points. Hours are recorded once for the whole subtopic.</p>}{list.map(o=><div className={`objective-row ${objectiveDone(c,item,o)?'objective-done':''}`} key={o.code}><Checkbox aria-label={`${o.code}: ${o.title}`} checked={objectiveDone(c,item,o)} disabled={disabled} onCheckedChange={v=>onObjective(o,v===true)}/><details className="objective"><summary><span className="objective-code">{o.code}{o.hl?' · HL only':''}</span><span>{o.title}</span><span className="disclosure-icon" aria-hidden="true">⌄</span></summary><ul>{o.points.map(point=><li key={point}>{point}</li>)}</ul></details></div>)}</details>
}
function Hours({value,min,disabled,save,label}:{value:number;min:number;disabled:boolean;save:(value:number)=>void;label:string}){const [draft,setDraft]=useState(String(value));return <input aria-label={label} type="number" inputMode="decimal" min={min} max={1000} step={.25} value={draft} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={e=>{if(draft===''||!e.target.validity.valid){setDraft(String(value));return}const n=Number(draft);if(n!==value)save(n)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>}
