'use client';
import {useEffect,useState} from 'react';
import {onAuthStateChanged,signInWithPopup,signOut,type User} from 'firebase/auth';
import {collection,doc,getDocs,serverTimestamp,setDoc} from 'firebase/firestore';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {curriculum,getProgress,metrics,sourceUrl,type ClassRecord,type Level,type Item} from './curriculum';
import {auth,db,firebaseConfigured,googleProvider} from './firebase';
const fmt=(n:number)=>Number(n.toFixed(1)).toString();
export default function Tracker(){
 const [user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(!firebaseConfigured),[classes,setClasses]=useState<ClassRecord[]>([]),[selected,setSelected]=useState(''),[loaded,setLoaded]=useState(!firebaseConfigured),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[name,setName]=useState(''),[level,setLevel]=useState<Level>('SL'),[saved,setSaved]=useState('');
 const signedIn=Boolean(user);
 const c=classes.find(x=>x.id===selected); const sections=c?curriculum(c.level):[];const m=c?metrics(c):null;
 async function load(currentUser:User){if(!db)return;setLoaded(false);setError('');try{const snapshot=await getDocs(collection(db,'users',currentUser.uid,'classes'));const next=snapshot.docs.map(x=>x.data() as ClassRecord);setClasses(next);setSelected(old=>next.some(x=>x.id===old)?old:next[0]?.id||'')}catch(e){setError(friendlyError(e))}finally{setLoaded(true)}}
 useEffect(()=>{if(!auth)return;return onAuthStateChanged(auth,next=>{setUser(next);setAuthReady(true);if(next)void load(next);else{setClasses([]);setSelected('');setLoaded(true)}})},[]);
 async function login(){if(!auth)return;setError('');try{await signInWithPopup(auth,googleProvider)}catch(e){if((e as {code?:string}).code!=='auth/popup-closed-by-user')setError(friendlyError(e))}}
 async function logout(){if(!auth)return;setError('');try{await signOut(auth)}catch(e){setError(friendlyError(e))}}
 async function create(e:React.FormEvent){e.preventDefault();if(!db||!user)return;setBusy(true);setError('');try{const next:ClassRecord={id:crypto.randomUUID(),name:name.trim(),level,minutes:50,progress:{}};await setDoc(doc(db,'users',user.uid,'classes',next.id),{...next,updatedAt:serverTimestamp()});setClasses(old=>[...old,next]);setSelected(next.id);setOpen(false);setName('');setSaved('Class saved')}catch(e){setError(friendlyError(e))}finally{setBusy(false)}}
 async function update(next:ClassRecord){if(busy||!db||!user)return;setBusy(true);setError('');setSaved('Saving…');try{await setDoc(doc(db,'users',user.uid,'classes',next.id),{...next,updatedAt:serverTimestamp()},{merge:true});setClasses(old=>old.map(x=>x.id===next.id?next:x));setSaved('All changes saved')}catch(e){setError(friendlyError(e));setSaved('Not saved')}finally{setBusy(false)}}
 function change(item:Item,key:'done'|'planned'|'taught',value:number|boolean){if(!c)return;return update({...c,progress:{...c.progress,[item.id]:{...getProgress(c,item),[key]:value}}})}
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(configuration:unknown,options?:unknown)=>unknown}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();try{Promise.resolve(ctx.registerTool({name:'read_curriculum_progress',description:'Read the selected class, completion, teaching hours and subtopic status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return c?{className:c.name,level:c.level,...metrics(c),sections:curriculum(c.level).map(s=>({...s,items:s.items.map(i=>({...i,...getProgress(c,i)}))}))}:{selectedClass:null}}},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[c]);
 return <><header><div className="brand"><span className="brand-mark">✓</span> Curriculum Compass</div><div className="account">{user?<><span>{user.displayName||user.email}</span><button className="account-link" onClick={logout}>Sign out</button></>:firebaseConfigured?<button className="account-link" onClick={login}>Sign in with Google</button>:<span>Setup pending</span>}</div></header><main><div className="eyebrow">IB Computer Science · First assessment 2027</div><div className="titleline"><h1>Your teaching, at a glance.</h1></div><p className="muted">Follow each class from the first subtopic to the final lesson.</p>
 {error&&<div role="alert" className="error">{error} {user&&!loaded&&<button onClick={()=>load(user)}>Retry loading</button>}</div>}
 {!firebaseConfigured?<section className="empty" style={{marginTop:24}}><h2>Firebase setup is nearly finished</h2><p className="muted">Add the six Firebase repository variables listed in the README, then run the GitHub Pages workflow again.</p></section>:!authReady?<p role="status" style={{marginTop:24}}>Checking your sign-in…</p>:!signedIn?<section className="empty" style={{marginTop:24}}><h2>Keep every class in its own workspace</h2><p className="muted">Sign in with Google to create an SL or HL class and save your curriculum progress and teaching hours.</p><button className="primary" style={{marginTop:16}} onClick={login}>Sign in with Google</button></section>:!loaded?<p role="status" style={{marginTop:24}}>Loading your classes…</p>:<>
 <div className="toolbar"><div style={{display:'flex',gap:12,alignItems:'center'}}>{classes.length>0&&<Select value={selected} onValueChange={setSelected} disabled={busy}><SelectTrigger aria-label="Choose class" style={{width:280,maxWidth:'100%',height:44,background:'white'}}><SelectValue/></SelectTrigger><SelectContent>{classes.map(x=><SelectItem key={x.id} value={x.id}>{x.name} · {x.level}</SelectItem>)}</SelectContent></Select>}<span className="saving" role="status">{saved}</span></div><button className="primary" disabled={busy} onClick={()=>setOpen(true)}>+ New class</button></div>
 {!c?<section className="empty"><h2>Create your first class</h2><p className="muted">Give it a name, choose SL or HL, and start with the matching curriculum and IB topic-hour totals.</p></section>:m&&<>
 <div className="titleline"><h2>{c.name}</h2><span className="level">{c.level==='SL'?'Standard level':'Higher level'}</span></div>
 <div className="stats"><section className="stat"><span>Course completion</span><strong>{Math.round(m.done/m.count*100)}%</strong><Progress value={m.done/m.count*100} aria-label="Course completion"/><p className="muted" style={{fontSize:14,marginTop:12}}>{m.done} of {m.count} checklist items complete</p></section><section className="stat"><span className="muted">Teaching time logged</span><strong>{fmt(m.taught)} <small style={{fontSize:17,fontWeight:400}}>hours</small></strong><p className="muted">of {fmt(m.planned)} planned hours</p><p className="muted" style={{fontSize:14}}>IB course recommendation: {c.level==='SL'?150:240} h</p></section><section className="stat"><span className="muted">Completion by planned hours</span><strong>{Math.round(m.weighted)}%</strong><p className="muted">{fmt(m.remaining)} h of allocated time remaining</p><p className="muted" style={{fontSize:14}}>≈ {Math.ceil(m.remaining*60/c.minutes)} lessons at {c.minutes} min</p></section></div>
 <div className="plan-settings"><label htmlFor="lesson-minutes">Minutes per lesson</label><NumberField key={`${c.id}-minutes-${c.minutes}`} id="lesson-minutes" value={c.minutes} min={10} max={240} step={1} disabled={busy} save={v=>update({...c,minutes:v})}/><span className="muted">Hours are 60-minute teaching hours.</span></div>
 <div className="notice"><strong>IB totals, flexible lesson planning.</strong> Topic totals follow the guide. Subtopic hour splits are editable planning estimates; include practice and assessment in those allocations. Check a subtopic when it has been taught and checked for understanding, including HL extensions where applicable. Logging hours does not check it off.</div>
 <div className="titleline" style={{margin:'26px 0 14px'}}><h2>Curriculum checklist</h2><span className="muted" style={{fontSize:14}}>Open a topic to update progress</span></div>
 {sections.map((s,idx)=>{const rows=s.items.map(i=>getProgress(c,i)),done=rows.filter(r=>r.done).length,planned=rows.reduce((a,r)=>a+r.planned,0),ib=s.items.reduce((a,i)=>a+i.hours,0);return <details className="section" key={`${c.id}-${s.id}`} open={idx===0?true:undefined}><summary><span className="code">{s.id}</span><div className="section-title"><h2>{s.title}</h2><span className="muted" style={{fontSize:13}}>{done}/{s.items.length} complete · IB {ib} h{planned!==ib?` · Your plan ${fmt(planned)} h`:''}</span></div><div className="section-meta"><span>{Math.round(done/s.items.length*100)}%</span><Progress value={done/s.items.length*100} aria-label={`${s.title} completion`}/></div></summary><div className="row colhead"><span/><span>Subtopic / component</span><span>Planned h</span><span>Taught h</span></div>{s.items.map(item=>{const r=getProgress(c,item);return <div className={`row ${r.done?'done':''}`} key={item.id}><Checkbox id={`${c.id}-${item.id}`} checked={r.done} disabled={busy} onCheckedChange={v=>change(item,'done',v===true)} style={{width:20,height:20}}/><label htmlFor={`${c.id}-${item.id}`}><span className="muted" style={{display:'block',fontSize:12,marginBottom:4}}>{item.id}{item.hl?' · HL only':''}</span>{item.title}</label><NumberField key={`${c.id}-${item.id}-p-${r.planned}`} label={`${item.id} planned hours`} value={r.planned} min={0.25} disabled={busy} save={v=>change(item,'planned',v)}/><NumberField key={`${c.id}-${item.id}-t-${r.taught}`} label={`${item.id} taught hours`} value={r.taught} min={0} disabled={busy} save={v=>change(item,'taught',v)}/></div>})}</details>})}
 <p className="bottom-note">Completion counts each subtopic and the three course components once. The time-weighted percentage uses your planned hours. Remaining time sums each allocation’s unused hours; it does not estimate mastery or automatically remove completed topics.</p></>}
 </>}
 <Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogHeader><DialogTitle>Create a class</DialogTitle><DialogDescription>Each class gets its own saved checklist and teaching plan.</DialogDescription></DialogHeader><form onSubmit={create} className="formgrid"><label>Class name<input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Period 3 · IB CS 2027" disabled={busy}/></label><label>Curriculum<Select value={level} onValueChange={v=>setLevel(v as Level)} disabled={busy}><SelectTrigger aria-label="Curriculum level" style={{width:'100%'}}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="SL">SL · 150 recommended hours</SelectItem><SelectItem value="HL">HL · 240 recommended hours</SelectItem></SelectContent></Select></label>{error&&<p role="alert" className="error">{error}</p>}<button type="submit" className="primary" disabled={busy||!name.trim()}>{busy?'Creating…':'Create class'}</button></form></DialogContent></Dialog>
 <footer>Based on the <a href={sourceUrl} target="_blank" rel="noreferrer">IB Computer Science guide, first assessment 2027</a>, printed pages 25–26. Independent teaching planner; not affiliated with the IB.</footer>
 </main></>
}
function NumberField({value,save,label,id,min,disabled,max=1000,step=.25}:{value:number;save:(n:number)=>unknown;label?:string;id?:string;min:number;disabled:boolean;max?:number;step?:number}){const [draft,setDraft]=useState(String(value));return <input id={id} aria-label={label} type="number" inputMode="decimal" value={draft} min={min} max={max} step={step} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={e=>{const v=Number(draft);if(draft===''||!e.target.validity.valid){setDraft(String(value));return}if(v!==value)save(v)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>}
function friendlyError(error:unknown){const code=(error as {code?:string}).code;if(code==='auth/unauthorized-domain')return 'Google sign-in is not authorized for this website yet. Add ostromaj.github.io in Firebase Authentication → Settings → Authorized domains.';if(code==='permission-denied')return 'Firebase blocked this request. Publish the Firestore rules included with this project.';return (error as Error)?.message||'Unable to connect. Please retry.'}
